api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        pagination_enabled: false
    title: 'BileMo API'
    description: 'La vitrine de téléphones mobiles de l’entreprise BileMo'
    version: '2.0.0'
    show_webby: false
    enable_swagger_ui: false
    enable_re_doc: false
